spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/add-service-demo-log

kafka:
  bootstrapServers: kafka-server:9092
  groupId: mongo
  enableAutoCommit: true
  autoCommitIntervalMs: 100
  sessionTimeOutMs: 15000
