server:
  port: 80

zuul:
  routes:
    add-service-demo:
      path: /add-service/**
      serviceId: add-service-demo

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
