spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @activatedProperties@

server:
  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    enableSelfPreservation: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false