server:
  port: 9411

spring:
  profiles:
    active: @activatedProperties@
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://192.168.0.126:3306/sleuth_log
    username: root
    password: 123456
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
  output:
    ansi:
      enabled: ALWAYS

zipkin:
  storage:
    type: mysql